//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_accounts
    {
        public int acc_id { get; set; }
        public string acc_no { get; set; }
        public Nullable<double> amt { get; set; }
    }
}
